# Generated by Django 5.1.4 on 2025-02-01 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('mot_de_passe', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FormDataSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('date_enregistrement', models.DateField(blank=True, null=True)),
                ('lieu_activite', models.CharField(choices=[('Lieu 1', 'Lieu 1'), ('Lieu 2', 'Lieu 2'), ('Lieu 3', 'Lieu 3'), ('Lieu 4', 'Lieu 4'), ('Lieu 5', 'Lieu 5')], max_length=100)),
                ('stock_sim_activees', models.PositiveIntegerField(blank=True, null=True)),
                ('stock_sim_blanches', models.PositiveIntegerField(blank=True, null=True)),
                ('sim_appro', models.PositiveIntegerField(blank=True, null=True)),
                ('effectif_total', models.PositiveIntegerField(blank=True, null=True)),
                ('effectif_present', models.PositiveIntegerField(blank=True, null=True)),
                ('gsm', models.PositiveIntegerField(blank=True, null=True)),
                ('momo_app', models.PositiveIntegerField(blank=True, null=True)),
                ('mymtn', models.PositiveIntegerField(blank=True, null=True)),
                ('ayoba', models.PositiveIntegerField(blank=True, null=True)),
                ('telephone', models.PositiveIntegerField(blank=True, null=True)),
                ('modem', models.PositiveIntegerField(blank=True, null=True)),
                ('mifi', models.PositiveIntegerField(blank=True, null=True)),
                ('wifix', models.PositiveIntegerField(blank=True, null=True)),
                ('difficultes', models.TextField(blank=True, null=True)),
                ('momoconvertion', models.PositiveIntegerField(blank=True, null=True)),
                ('resetpin', models.PositiveIntegerField(blank=True, null=True)),
                ('prospection', models.TextField(blank=True, null=True)),
                ('besoin', models.TextField(blank=True, null=True)),
                ('concurrentielle', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
