# Generated by Django 5.1.4 on 2025-02-28 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdatasupervisor',
            name='lieu_activite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='MoMoPayMassMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('date_enregistrement', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateField()),
                ('heure_creation', models.TimeField()),
                ('nom_merchant', models.CharField(max_length=255)),
                ('nom_etablissement', models.CharField(max_length=255)),
                ('localisation_merchant', models.CharField(max_length=255)),
                ('reference_adresse', models.TextField(blank=True, null=True)),
                ('secteur_activite', models.CharField(max_length=100)),
                ('numero_merchant', models.CharField(max_length=50, unique=True)),
                ('identifiant_merchant', models.CharField(max_length=50, unique=True)),
                ('montant_transaction', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
