# Generated by Django 5.1.4 on 2025-02-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_alter_formdatasupervisor_lieu_activite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdatasupervisor',
            name='lieu_activite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
