# Generated by Django 5.1.4 on 2025-03-01 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_alter_formdatasupervisor_lieu_activite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RAPPORT_GSM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('données', models.TextField()),
                ('superviseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_view_all_gsm', 'Peut voir tous les rapports GSM'), ('can_view_own_gsm', 'Peut voir ses propres rapports GSM'), ('can_view_all', 'Peut voir tous les rapports (GSM et MoMoPay)')],
            },
        ),
        migrations.CreateModel(
            name='RAPPORT_MOMOPAY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('données', models.TextField()),
                ('superviseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_view_all_momopay', 'Peut voir tous les rapports MoMoPay'), ('can_view_own_momopay', 'Peut voir ses propres rapports MoMoPay'), ('can_view_all', 'Peut voir tous les rapports (GSM et MoMoPay)')],
            },
        ),
    ]
